name: Deploy app on github.io
on:
    push:
        branches:
            - release
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+' # v25.1.0

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow one concurrent deployment
concurrency:
    group: 'pages'
    cancel-in-progress: true

jobs:
    greeting:
        runs-on: ubuntu-latest
        steps:
            - name: Echo a greeting message
              run: echo "Hello from custom deploy action👋"
    verify-tag:
        runs-on: ubuntu-latest
        steps: # TODO
            - name: TEST
              run: echo "test verify-tag job"
    build:
        needs: verify-tag
        strategy:
            matrix:
                version: [20, 21]
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        continue-on-error: true
        steps:
            - name: Share repository for workspace runner
              uses: actions/checkout@v4
            - name: Set up NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.version }}
            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install dependencies
              run: npm ci || npm install --omit=dev
            - name: Build
              run: npm run build
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  path: build
                  name: app-build-${{ matrix.os }}-${{ matrix.version }}
    deploy:
        needs: [verify-tag, build]
        strategy:
            matrix:
                version: [20]
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                  path: build
                  name: app-build-${{ matrix.os }}-${{ matrix.version }}
            - name: Test downloaded artifacts
              run: ls -R build
            - name: Setup Pages
              uses: actions/configure-pages@v4
            - name: Upload pages artifacts
              uses: actions/upload-pages-artifact@v3
              with:
                  path: 'build'
                  name: app-build-${{ matrix.os }}-${{ matrix.version }}
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
